-- SQLite
CREATE TABLE Products (
    ID TEXT PRIMARY KEY,
    PRODUCT_NAME TEXT,
    PRICE INTEGER,
    CATEGORY TEXT,
    REVIEW_PERSON TEXT,
    RATE INTEGER,
    COMMENT TEXT,
    DESCRIPTION TEXT
);

INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p1', 'Wireless Headphone', 15000, 'Electronics', 'Alice', 5, 'Nice', 'Compact portable speaker with powerful sound and long battery life.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p17', 'Portable Speaker', 9000, 'Electronics', 'Manahil', 5, 'good', 'High-fidelity sound with noise cancellation, perfect for immersive audio experiences.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p18', 'Gaming Mouse', 5000, 'Electronics', 'Ali', 4, 'quality is soft', 'Ergonomic gaming mouse with customizable RGB lighting and high DPI.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p2', 'Smart Watch', 30000, 'Electronics', 'Bob', 4, 'amazing product', 'Track your fitness, receive notifications, and manage calls directly from your wrist.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p3', 'Casual T-Shirt', 3500, 'Clothing', 'Charlie', 5, 'Nice', 'Comfortable 100% cotton t-shirt for everyday wear. Available in multiple colors and sizes.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p4', 'Denim jeans', 8500, 'Clothing', 'Diana', 4, 'good', 'Classic fit denim jeans, durable and stylish for any occasion.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p5', 'Coffee Maker', 12000, 'Home & Good', 'Eve', 5, 'amazing product', 'Brew perfect coffee every morning with this easy-to-use coffee maker.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p6', 'Desk Lamb', 5000, 'Home & Good', 'Frank', 3, 'cool and ok', 'Modern desk lamp with adjustable brightness and color temperature.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p7', 'Sci-Fi Epic Novel', 2500, 'Books', 'Grace', 5, 'quality is soft', 'A thrilling science fiction novel with intricate world-building and compelling characters.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p8', 'Yoga Mat', 4000, 'Sports & Outdoors', 'Heidi', 4, 'good', 'Durable and non-slip yoga mat, ideal for all types of yoga and fitness exercises.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p9', 'Natural Face Serum', 6500, 'Beauty', 'Ivy', 5, 'excellent way and quality', 'Organic face serum with hyaluronic acid for hydration and anti-aging benefits.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p10', 'Wooden Building Blocks', 5500, 'Kids & Toys', 'Jack', 5, 'pretty', 'Classic wooden building blocks set for creative play and developing motor skills.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p11', 'Orthopedic Dog Bed', 13000, 'Pet Supplies', 'Karen', 4, 'amazing product', 'Comfortable orthopedic dog bed designed for joint support and ultimate pet comfort.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p12', 'Car Vaccum Cleaner', 7000, 'Automative', 'Liam', 3, 'excellent way and quality', 'Portable and powerful car vacuum cleaner for quick and easy interior cleaning.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p13', 'Smart Garden System', 18000, 'Garden & Outdoors', 'Mia', 5, 'quality is soft', 'Automated indoor garden system for growing herbs and vegetables year-round.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p14', 'Silver Pendant Necklace', 10000, 'Jewelry', 'Noah', 5, 'good', 'Elegant sterling silver pendant necklace with a delicate chain, perfect for any outfit.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p15', 'Artisan Coffee Beans', 2300, 'Food & Drink', 'Olivia', 5, 'Nice', 'Premium single-origin coffee beans, medium roast with notes of chocolate and caramel.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p16', 'Aromatherapy Diffuser', 5000, 'Health & Wellness', 'Peter', 4, 'good', 'Ultrasonic essential oil diffuser with LED lighting, creates a relaxing ambiance.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p19', 'Security Camera', 8000, 'Electronics', 'Maha', 4, 'cool and ok', 'Indoor security camera with motion detection and night vision.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p20', 'Laptop', 60000, 'Electronics', 'Ahmad', 3, 'perfect', 'Powerful laptop for work and entertainment, lightweight design.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p21', 'Led', 50000, 'Electronics', 'Sara', 4, 'no fault', 'LED TV shows clearer and brighter pictures with lower power use.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p22', 'Printer', 65000, 'Electronics', 'Ahmad', 3, 'cool and ok', 'A printer gives you a paper copy of your digital work, like notes or photos.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p23', 'Moisturizing Cream', 2500, 'Beauty', 'Taha', 4, 'amazing product', 'Hydrating and nourishing cream for all skin types.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p24', 'Lipstick Set', 3500, 'Beauty', 'Manahil', 5, 'perfect', 'Collection of long-lasting lipsticks in various shades.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p25', 'Eye Shadow Palette', 4000, 'Beauty', 'Maha', 4, 'pretty', 'Versatile eye shadow palette with matte and shimmer shades.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p26', 'Blush', 1500, 'Beauty', 'Ivy', 5, 'no fault', 'Powder blush for a natural, healthy glow.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p27', 'Perfume', 6500, 'Beauty', 'Ivy', 5, 'Nice', 'Elegant perfume with a floral and musky scent.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p28', 'Brushes', 2500, 'Beauty', 'sara', 5, 'quality is soft', 'Beauty brushes help apply and blend makeup smoothly for a flawless look.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p29', 'Eye liner', 1000, 'Beauty', 'maham', 5, 'excellent way and quality', 'Eyeliner defines and enhances the eyes, creating bold or subtle looks.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p97', 'Mystery Thriller', 1250, 'Books', 'Grace', 5, 'Nice', 'A gripping mystery thriller with unexpected twists and turns.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p30', 'Cooking Recipe Book', 2200, 'Books', 'Grace', 5, 'good', 'A comprehensive cooking recipe book for all skill levels.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p31', 'Self Help Guide', 1800, 'Books', 'Grace', 5, 'amazing product', 'A practical self-help guide to improve productivity and well-being.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p32', 'Fantasy Epic', 4000, 'Books', 'Charlie', 5, 'cool and ok', 'An epic fantasy novel with a rich world and compelling characters.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p33', 'Casual T-Shirt Mens', 3500, 'Clothing', 'Charlie', 5, 'perfect', 'Comfortable 100% cotton t-shirt for everyday wea.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p34', 'Denim jeans Mens', 8500, 'Clothing', 'Charlie', 5, 'pretty', 'Classic fit denim jeans, durable and stylish for any occasion.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p35', 'Casual T-Shirt Women', 3500, 'Clothing', 'Charlie', 5, 'quality is soft', 'Comfortable 100% cotton t-shirt for everyday wea.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p36', 'Denim jeans Women', 8500, 'Clothing', 'Diana', 4, 'no fault', 'Classic fit denim jeans, durable and stylish for any occasion.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p98', 'Casual T-Shirt Women', 3500, 'Clothing', 'Mia', 5, 'amazing product', 'Comfortable 100% cotton t-shirt for everyday wea.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p99', 'Denim jeans Women', 8500, 'Clothing', 'Mia', 5, 'Nice', 'Classic fit denim jeans, durable and stylish for any occasion.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p37', 'Smart Outdoor System', 30000, 'Garden & Outdoors', 'Mia', 5, 'perfect', 'Smart outdoor system is an automated setup that controls garden lighting.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p38', 'Smart Outdoor System', 50000, 'Garden & Outdoors', 'Mia', 5, 'cute', 'Smart outdoor system is an automated setup that controls garden lighting.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p39', 'Smart Outdoor System', 48000, 'Garden & Outdoors', 'Mia', 5, 'workable products', 'Smart outdoor system is an automated setup that controls garden lighting.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p40', 'Smart Outdoor System', 58000, 'Garden & Outdoors', 'Mia', 5, 'trustable', 'Smart outdoor system is an automated setup that controls garden lighting.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p41', 'Smart Garden System', 38000, 'Garden & Outdoors', 'Mia', 5, 'cool and ok', 'Smart garden system automatically waters and cares for plants for easy gardening.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p42', 'Smart Garden System', 70000, 'Garden & Outdoors', 'Liam', 3, 'no fault', 'Smart garden system automatically waters and cares for plants for easy gardening.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p43', 'Smart Garden System', 88000, 'Garden & Outdoors', 'Liam', 3, 'amazing product', 'Smart garden system automatically waters and cares for plants for easy gardening.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p44', 'Mirror', 5000, 'Automative', 'Olivia', 5, 'trustable', 'Portable and powerful mirror.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p45', 'Tires', 7000, 'Automative', 'Olivia', 5, 'perfect', 'long time tiers.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p46', 'Coke', 500, 'Food & Drink', 'Olivia', 5, 'good', 'very tasty.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p47', 'Biryani', 250, 'Food & Drink', 'Olivia', 5, 'amazing product', 'yummy to eat.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p48', 'Pasta', 250, 'Food & Drink', 'Olivia', 5, 'cute', 'yummy to eat.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p49', 'White Karahi', 250, 'Food & Drink', 'Olivia', 5, 'excellent way and quality', 'yummy to eat.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p50', 'Roll Paratha', 250, 'Food & Drink', 'Olivia', 5, 'perfect', 'yummy to eat.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p51', 'Sprite', 500, 'Food & Drink', 'Sadia', 5, 'cool and ok', 'very tasty.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p52', 'Mirinda', 500, 'Food & Drink', 'Noah', 5, 'no fault', 'very tasty.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p53', 'Rings', 5000, 'Jewelry', 'Noah', 4, 'trustable', 'Stylish finger bands that add elegance to any outfit.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p54', 'Bridle Set Golden', 20000, 'Jewelry', 'Noah', 4, 'workable products', 'Luxurious golden bridal jewelry set for weddings.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p55', 'Bridle Set Silver', 17000, 'Jewelry', 'Palwisha', 5, 'no issue', 'Elegant silver bridal jewelry set with a classic look.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p56', 'Crown', 7000, 'Jewelry', 'amina', 5, 'amazing product', 'Decorative headpiece that adds a royal touch.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p57', 'Necklace', 10000, 'Jewelry', 'Noah', 5, 'quality is soft', 'Beautiful chain or pendant worn around the neck.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p58', 'Jhumar', 1000, 'Jewelry', 'Heidi', 5, 'cute', 'Traditional hair ornament that enhances bridal beauty.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p59', 'Earings', 1000, 'Jewelry', 'Heidi', 5, 'amazing product', 'Decorative pieces worn on the ears for style and charm.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p60', 'Water Bottle', 1500, 'Sports & Outdoors', 'maham', 5, 'trustable', 'Portable container for carrying drinking water anywhere.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p61', 'Camping Tent', 15000, 'Sports & Outdoors', 'jack', 5, 'Nice', 'Foldable shelter for outdoor camping and adventures.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p62', 'Fitness Tracker', 8000, 'Sports & Outdoors', 'jack', 5, 'no fault', 'Wearable device that monitors health and activity.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p63', 'Board Game', 7500, 'Kids & Toys', 'nouman', 3, 'no issue', 'Fun tabletop game played with family or friends.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p64', 'Remote Control Car', 15000, 'Kids & Toys', 'farzam', 4, 'cool and ok', 'Toy car operated using a wireless remote.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p65', 'Orthopedic Dog Bed', 15000, 'Pet Supplies', 'Ali', 5, 'trustable', 'Comfortable orthopedic dog bed designed for joint support and ultimate pet comfort.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p66', 'Orthopedic Cat Bed', 13000, 'Pet Supplies', 'Manahil', 3, 'amazing product', 'Comfortable orthopedic cat bed designed for joint support and ultimate pet comfort.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p67', 'Orthopedic Cat Bed', 16000, 'Pet Supplies', 'mahreen', 3, 'perfect', 'Comfortable orthopedic cat bed designed for joint support and ultimate pet comfort.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p68', 'Car Polish', 2000, 'Automative', 'Liam', 3, 'excellent way and quality', 'shinny look.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p69', 'Car Speakers', 10000, 'Automative', 'sadia', 5, 'cute', 'amazing sound quality.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p70', 'Car Tool Kit', 9000, 'Automative', 'Sadia', 5, 'amazing product', 'every tool kit of car.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p71', 'Seat Cover', 4000, 'Automative', 'Grace', 5, 'Nice', 'clean and soft.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p72', 'Led Highlights Of Car', 9000, 'Automative', 'Ahmad', 5, 'pretty', 'light reflection is soo cool.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p73', 'Computer Neywork Book', 500, 'Books', 'Ali', 5, 'good', 'A computer network is a group of connected computers that can share data.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p74', 'Harry Potter Series', 4000, 'Books', 'Ali', 5, 'amazing product', 'The Harry Potter series is a magical adventure about a young wizard.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p75', 'Parrot', 9000, 'Pet Supplies', 'Maha', 5, 'excellent way and quality', 'Comfortable orthopedic parrot bed designed for joint support.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p76', 'Rabbit', 8000, 'Pet Supplies', 'Manahil', 5, 'cute', 'Rabbit bed designed for joint support and ultimate pet comfort.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p77', 'Duck', 6000, 'Pet Supplies', 'maham', 5, 'workable products', 'Duck bed designed for joint support and ultimate pet comfort.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p78', 'Goat', 9000, 'Pet Supplies', 'jack', 5, 'trustable', 'goat designed for joint support and ultimate pet comfort.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p79', 'Doll House', 4500, 'Kids & Toys', 'Manahil', 5, 'quality is soft', 'A mini home where kids play and arrange tiny furniture with dolls.'); 
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p80', 'Puzzle', 4400, 'Kids & Toys', 'maham', 5, 'good', 'A brain game where kids join pieces to make a full picture.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p81', 'Train Toy', 3000, 'Kids & Toys', 'maham', 5, 'Nice', 'A fun toy train that kids push or run on tracks.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p82', 'Teady Bear', 12000, 'Kids & Toys', 'maham', 5, 'quality is soft', 'A soft, cuddly stuffed toy that children love to hug.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p83', 'Colouring book', 400, 'Kids & Toys', 'Peter', 4, 'no issue', 'A book with pictures for kids to fill with colors.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p84', 'Resistance Bands Set', 2000, 'Sports & Outdoors', 'Peter', 4, 'no fault', 'Stretchy fitness bands used for exercise and muscle training.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p85', 'Badminton Racket', 1500, 'Sports & Outdoors', 'Peter', 4, 'excellent way and quality', 'A lightweight racket used to hit the shuttlecock in badminton.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p86', 'Bat & Ball', 5000, 'Sports & Outdoors', 'Peter', 4, 'Nice', 'A classic outdoor set for playing cricket or casual ball games.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p87', 'First Aid Kit', 3000, 'Health & Wellness', 'waseem', 5, 'no issue', 'A box with basic medical items for treating small injuries at home.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p88', 'Blood Pressure Moniter', 7000, 'Health & Wellness', 'samreen', 4, 'amazing product', 'A device to check and track your blood pressure easily.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p89', 'Face Mask', 200, 'Health & Wellness', 'laiba', 5, 'trustable', 'A protective cover for the nose and mouth to prevent germs and dust.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p90', 'Hand Sanitizer', 200, 'Health & Wellness', 'maha', 3, 'amazing product', 'A quick-dry liquid or gel used to kill germs without water.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p91', 'Pillow', 2500, 'Home & Good', 'eve', 3, 'no issue', 'A small soft cushion used for comfort and decoration on sofas or beds.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p92', 'Wall Art Print', 5000, 'Home & Good', 'sana', 5, 'perfect', 'A printed picture or design to hang on walls for a stylish look.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p93', 'Scented Candles Set', 2000, 'Home & Good', 'Manahil', 5, 'pretty', 'Fragrant candles that create a calm and cozy atmosphere.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p94', 'Bedsheet', 3000, 'Home & Good', 'Alice', 4, 'Nice', 'A fabric layer spread over the bed for comfort and cleanliness.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p95', 'Mirror', 10000, 'Home & Good', 'samreen', 2, 'cool and ok', 'A glass surface that reflects your image, often used for dressing.');
INSERT INTO Products (ID, PRODUCT_NAME, PRICE, CATEGORY, REVIEW_PERSON, RATE, COMMENT, DESCRIPTION) VALUES ('p96', 'Laundry Basket', 9000, 'Home & Good', 'Mia', 4, 'excellent way and quality', 'A container used to collect and carry dirty clothes.');

SELECT * FROM Products;
